# Generated by Django 5.2.8 on 2025-12-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_member_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('event', 'Event'), ('workshop', 'Workshop'), ('competition', 'Competition'), ('special', 'Special Class')], default='event', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SpecialHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closure_type', models.CharField(choices=[('holiday', 'Holiday'), ('closure', 'Closure'), ('modified', 'Modified Hours')], default='holiday', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('is_closed', models.BooleanField(default=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Special Hours',
                'verbose_name_plural': 'Special Hours',
                'ordering': ['date'],
            },
        ),
    ]
