# Generated by Django 5.2.8 on 2025-12-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_gymevent_specialhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('years_experience', models.IntegerField(default=1)),
                ('certifications', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
