# Generated by Django 5.2.8 on 2025-12-09 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
